### ISSUE TITLE
web push to logged in user

### ISSUE THREAD

**Issue by interfaith** [vkarpov15/web-push-demo#1]
Can this work so when a chrome user subscribes, then the notification goes to any chrome browser the user is logged in to ?

**Comment by interfaith** [comment]
via an https express server  the app works as before, but does not notify another chrome open with the same login and subscribed via the same website.

**Comment by interfaith** [comment]
https://github.com/gauntface/web-push-book has all the 'details' thx  !

**Comment by vkarpov15** [comment]
@interfaith glad you found the answer. For your original question, yes, it can, you just need to keep track of all the user's subscriptions. In theory, you should be able to just store an array of subscriptions for a user and loop over it when you want to send a notification to the user.
